#!/bin/bash
if command -v python3 &> /dev/null; then
    python3 -u scf_index.py
elif command -v python &> /dev/null; then
    python -u scf_index.py
else
    # 直接使用绝对路径
    /var/lang/bin/python3.10 -u scf_index.py
fi
